name: future_mind_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: 3.3.9

dependencies:
  flutter:
    sdk: flutter

  # functional
  flutter_i18n: ^0.32.4
  dio: ^5.0.2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.10

  # routing
  auto_route: ^5.0.3

  # state management
  flutter_bloc: ^8.1.2
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0

  # functional programming
  dartz: ^0.10.1
  intl: ^0.17.0

  # ui
  flutter_screenutil: ^5.7.0
  shimmer: ^2.0.0
  material_design_icons_flutter: ^5.0.6996
  google_fonts: ^4.0.3

  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5

### development
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mockito: ^5.4.0
  bloc_test: ^9.1.1
  http_mock_adapter: ^0.4.2

  # icon generator
  flutter_launcher_icons: "^0.13.1"
  import_sorter: ^4.6.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/graphics/news.png"

  #code generators
  build_runner: ^2.2.1
  auto_route_generator: ^5.0.2
  freezed: ^2.1.0+1
  json_serializable: ^6.5.1

  #code clarity
  lint: ^1.10.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/graphics/news.png
